apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: noope-gitops
  description: This is GitOps manifest for noope   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: noope
    janus-idp.io/tekton: noope 
    backstage.io/kubernetes-id: noope 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:noope
