apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: noope
  janus-idp.io/tekton: noope
  backstage.io/kubernetes-id: noope
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: noope
resources: 
- deployment.yaml
- route.yaml
- service.yaml
